# Generated by Django 5.2.8 on 2025-11-28 09:22

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(default=main.models.short_uuid, max_length=12, unique=True),
        ),
    ]
